// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpVCltpOHR6twc90S6VqI1qVnFFXhV6e8',
    appId: '1:867203524632:web:50d8660484a4833195bb6d',
    messagingSenderId: '867203524632',
    projectId: 'flutterfirebaru1',
    authDomain: 'flutterfirebaru1.firebaseapp.com',
    storageBucket: 'flutterfirebaru1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmYtjMZCTQG6BtjFrt6xTbxYouMcyf8ME',
    appId: '1:867203524632:android:3b42eac381ff93b895bb6d',
    messagingSenderId: '867203524632',
    projectId: 'flutterfirebaru1',
    storageBucket: 'flutterfirebaru1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Fr0eUPZL9kCE7Wn8GHtBRYhmX1XAN78',
    appId: '1:867203524632:ios:1343b1f0feabcb2d95bb6d',
    messagingSenderId: '867203524632',
    projectId: 'flutterfirebaru1',
    storageBucket: 'flutterfirebaru1.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Fr0eUPZL9kCE7Wn8GHtBRYhmX1XAN78',
    appId: '1:867203524632:ios:1343b1f0feabcb2d95bb6d',
    messagingSenderId: '867203524632',
    projectId: 'flutterfirebaru1',
    storageBucket: 'flutterfirebaru1.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpVCltpOHR6twc90S6VqI1qVnFFXhV6e8',
    appId: '1:867203524632:web:e1c924b0a8d0820195bb6d',
    messagingSenderId: '867203524632',
    projectId: 'flutterfirebaru1',
    authDomain: 'flutterfirebaru1.firebaseapp.com',
    storageBucket: 'flutterfirebaru1.appspot.com',
  );

}